'use client';

import { useCallback, useMemo, useState } from 'react';
import Link from 'next/link';
import {
  ReactFlow, Background, Controls, MiniMap, Handle, Position, addEdge,
  useNodesState, useEdgesState, type Node, type Edge, type Connection, type NodeProps, MarkerType
} from '@xyflow/react';
import { Activity, Bell, Bot, Box, Braces, ChevronDown, ChevronLeft, ChevronRight, CirclePlay, ClipboardList, Copy, Database, FileScan, GitBranch, Grid3X3, Mail, Menu, Mic2, PanelLeft, Play, Plus, Redo2, RotateCcw, Save, Search, Settings2, ShoppingCart, Sparkles, Store, Trash2, Undo2, Users, X, Zap, ZoomIn, ZoomOut } from 'lucide-react';
import { Brand } from './Brand';

type FlowData = { label: string; detail: string; kind: string; color: string; icon?: string };
type FlowNode = Node<FlowData, 'flow'>;

const initialNodes: FlowNode[] = [
  {id:'start',type:'flow',position:{x:90,y:220},data:{label:'New vendor request',detail:'Form submitted',kind:'Trigger',color:'#675cf5',icon:'play'}},
  {id:'voice',type:'flow',position:{x:340,y:110},data:{label:'Extract voice intent',detail:'Whisper · EN/YO',kind:'Voice',color:'#18c7d8',icon:'mic'}},
  {id:'lookup',type:'flow',position:{x:610,y:110},data:{label:'Vendor lookup',detail:'Preferred · Lagos',kind:'Vendor',color:'#f97316',icon:'store'}},
  {id:'condition',type:'flow',position:{x:610,y:330},data:{label:'Risk score gateway',detail:'Score is less than 40',kind:'Condition',color:'#f5ad32',icon:'branch'}},
  {id:'po',type:'flow',position:{x:880,y:220},data:{label:'Create purchase order',detail:'Finance approval',kind:'Vendor',color:'#f97316',icon:'cart'}},
  {id:'end',type:'flow',position:{x:1140,y:220},data:{label:'Notify requester',detail:'Email + voice',kind:'Action',color:'#22c55e',icon:'mail'}},
];
const initialEdges: Edge[] = [
  {id:'e1',source:'start',target:'voice',animated:true,style:{stroke:'#18c7d8'},markerEnd:{type:MarkerType.ArrowClosed,color:'#18c7d8'}},
  {id:'e2',source:'voice',target:'lookup',animated:true,style:{stroke:'#18c7d8'},markerEnd:{type:MarkerType.ArrowClosed,color:'#18c7d8'}},
  {id:'e3',source:'lookup',target:'condition',animated:true,markerEnd:{type:MarkerType.ArrowClosed}},
  {id:'e4',source:'condition',target:'po',animated:true,markerEnd:{type:MarkerType.ArrowClosed}},
  {id:'e5',source:'po',target:'end',animated:true,style:{stroke:'#22c55e'},markerEnd:{type:MarkerType.ArrowClosed,color:'#22c55e'}},
];

const palette = [
  {group:'Flow control',nodes:[['Start','Trigger','#675cf5','play'],['End','Action','#22c55e','box'],['Condition','Condition','#f5ad32','branch'],['Loop','Control','#675cf5','rotate'],['Variable','Data','#675cf5','braces']]},
  {group:'Integrations',nodes:[['API request','Integration','#675cf5','zap'],['Database','Integration','#675cf5','db'],['Email','Action','#675cf5','mail'],['Salesforce','Integration','#675cf5','cloud'],['SAP','Integration','#675cf5','box']]},
  {group:'AI & transform',nodes:[['AI analyze','AI','#675cf5','sparkle'],['Generate','AI','#675cf5','bot'],['Validate','AI','#675cf5','check'],['Transform','Data','#675cf5','braces']]},
  {group:'Voice & audio',nodes:[['Voice trigger','Voice','#18c7d8','mic'],['Speech to text','Voice','#18c7d8','activity'],['Text to speech','Voice','#18c7d8','audio']]},
  {group:'Vendor management',nodes:[['Vendor lookup','Vendor','#f97316','store'],['Purchase order','Vendor','#f97316','cart'],['Document OCR','Vendor','#f97316','scan']]},
] as const;

const icons: Record<string, React.ComponentType<{size?:number}>> = {play:CirclePlay,mic:Mic2,store:Store,branch:GitBranch,cart:ShoppingCart,mail:Mail,box:Box,rotate:RotateCcw,braces:Braces,zap:Zap,db:Database,cloud:Users,sparkle:Sparkles,bot:Bot,check:ClipboardList,activity:Activity,audio:Activity,scan:FileScan};

function CustomNode({data,selected}:NodeProps<FlowNode>){const Icon=icons[data.icon||'box']||Box;return <div className="flow-node" style={{'--node-color':data.color} as React.CSSProperties}><Handle type="target" position={Position.Left}/><div className="flow-node-head"><span className="flow-node-icon"><Icon size={13}/></span><span><strong>{data.label}</strong><small>{data.detail}</small></span></div><div className="flow-node-foot"><span>{data.kind}</span><span>{selected?'Selected':'Ready'}</span></div><Handle type="source" position={Position.Right}/></div>}

export function CanvasStudio(){
  const [nodes,setNodes,onNodesChange]=useNodesState<FlowNode>(initialNodes);const [edges,setEdges,onEdgesChange]=useEdgesState(initialEdges);
  const [selected,setSelected]=useState('voice');const [tab,setTab]=useState('All');const [search,setSearch]=useState('');const [voiceOpen,setVoiceOpen]=useState(false);const [vendorOpen,setVendorOpen]=useState(false);const [poOpen,setPoOpen]=useState(false);const [running,setRunning]=useState(false);const [sideOpen,setSideOpen]=useState(true);const [propsOpen,setPropsOpen]=useState(true);
  const selectedNode=nodes.find(n=>n.id===selected);const nodeTypes=useMemo(()=>({flow:CustomNode}),[]);
  const connect=useCallback((c:Connection)=>setEdges(es=>addEdge({...c,animated:true,markerEnd:{type:MarkerType.ArrowClosed}},es)),[setEdges]);
  const addNode=(p:readonly [string,string,string,string])=>{const id=`node-${Date.now()}`;setNodes(ns=>[...ns,{id,type:'flow',position:{x:420+Math.random()*300,y:190+Math.random()*220},data:{label:p[0],kind:p[1],color:p[2],icon:p[3],detail:'Click to configure'}}]);setSelected(id)};
  const updateSelected=(patch:Partial<FlowData>)=>setNodes(ns=>ns.map(n=>n.id===selected?{...n,data:{...n.data,...patch}}:n));
  const visiblePalette=palette.map(g=>({...g,nodes:g.nodes.filter(n=>(tab==='All'||(tab==='Voice'&&n[1]==='Voice')||(tab==='Vendor'&&n[1]==='Vendor'))&&n[0].toLowerCase().includes(search.toLowerCase()))})).filter(g=>g.nodes.length);
  const execute=()=>{setRunning(true);setTimeout(()=>setRunning(false),1900)};
  return <div className="app-page">
    <header className="app-header"><Brand dark href="/"/><button className="app-icon-btn" onClick={()=>setSideOpen(v=>!v)} aria-label="Toggle node palette"><PanelLeft size={17}/></button><div className="workflow-info"><strong>Vendor Onboarding · West Africa</strong><span><i className="live-dot"/> Saved just now · v1.8</span></div><div className="app-tools"><button className="app-icon-btn" aria-label="Undo"><Undo2 size={15}/></button><button className="app-icon-btn" aria-label="Redo"><Redo2 size={15}/></button><span className="tool-sep"/><button className="app-icon-btn" aria-label="Zoom out"><ZoomOut size={15}/></button><button className="app-icon-btn" aria-label="Zoom in"><ZoomIn size={15}/></button><button className="app-icon-btn" aria-label="Grid settings"><Grid3X3 size={15}/></button><span className="tool-sep"/><button className="app-icon-btn" onClick={()=>setVoiceOpen(true)} aria-label="Open voice assistant"><Mic2 size={16}/></button><button className="btn btn-primary" onClick={execute}>{running?<><Activity size={15}/> Running…</>:<><Play size={14}/><span>Execute</span></>}</button><button className="app-icon-btn" aria-label="Notifications"><Bell size={16}/></button><button className="user-pill"><span className="user-photo">AM</span><span style={{fontSize:10,fontWeight:750}}>Ada M.</span><ChevronDown size={12}/></button><button className="app-icon-btn" onClick={()=>setPropsOpen(v=>!v)} aria-label="Toggle properties"><Settings2 size={16}/></button></div></header>
    <div className="studio" style={{gridTemplateColumns:`${sideOpen?'248px':'0px'} 1fr ${propsOpen?'282px':'0px'}`}}>
      <aside className="studio-side" style={!sideOpen?{display:'none'}:undefined} aria-label="Node palette"><div className="studio-tabs">{['All','Voice','Vendor'].map(t=><button onClick={()=>setTab(t)} className={`studio-tab ${tab===t?'active':''}`} key={t}>{t}</button>)}</div><div className="studio-search"><Search size={14}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search 20+ nodes…"/></div><div className="palette">{visiblePalette.map(g=><div className="palette-group" key={g.group}><div className="palette-heading"><span>{g.group}</span><span>{g.nodes.length}</span></div><div className="palette-grid">{g.nodes.map((n)=>{const Icon=icons[n[3]]||Box;return <button className={`palette-node ${n[1]==='Voice'?'voice':n[1]==='Vendor'?'vendor':''}`} key={n[0]} onClick={()=>addNode(n)} draggable><i><Icon size={13}/></i><span>{n[0]}</span></button>})}</div></div>)}</div></aside>
      <main className="studio-canvas"><div className="canvas-topbar"><button className="app-icon-btn" title="Select"><Menu size={14}/></button><button className="app-icon-btn" title="Add node" onClick={()=>addNode(['New step','Action','#675cf5','plus'])}><Plus size={14}/></button><button className="app-icon-btn" title="Voice build" onClick={()=>setVoiceOpen(true)}><Mic2 size={14}/></button><button className="app-icon-btn" title="Save"><Save size={14}/></button></div><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onConnect={connect} onNodeClick={(_,n)=>setSelected(n.id)} fitView fitViewOptions={{padding:.25}} minZoom={.25} maxZoom={2}><Background gap={18} size={1} color="#d4d8e0"/><Controls position="bottom-left"/><MiniMap position="bottom-right" nodeColor={n=>(n.data as FlowData).color} maskColor="rgba(245,246,248,.72)"/></ReactFlow><div className="canvas-status"><span className="tag tag-green">6 nodes healthy</span><span className="tag tag-cyan">Ada + 2 live</span></div></main>
      <aside className="properties" style={!propsOpen?{display:'none'}:undefined} aria-label="Node properties"><div className="mobile-panel-handle panel-handle"/><div className="prop-head"><div className="prop-head-line"><span className="prop-head-icon"><Mic2 size={16}/></span><span><strong>{selectedNode?.data.label||'Select a node'}</strong><span>{selectedNode?.id||'No node selected'}</span></span></div></div>{selectedNode&&<><div className="prop-block"><div className="prop-block-title">General <ChevronDown size={13}/></div><label className="field-label">Node name</label><input className="field" value={selectedNode.data.label} onChange={e=>updateSelected({label:e.target.value})}/><label className="field-label">Description</label><textarea className="field" style={{height:65,paddingTop:8,resize:'vertical'}} value={selectedNode.data.detail} onChange={e=>updateSelected({detail:e.target.value})}/></div><div className="prop-block"><div className="prop-block-title">Configuration <ChevronDown size={13}/></div><label className="field-label">Provider</label><select className="field" defaultValue="whisper"><option value="whisper">Whisper large-v3</option><option value="native">Browser native</option></select><label className="field-label">Language</label><select className="field" defaultValue="auto"><option value="auto">Auto-detect</option><option>English + Yorùbá</option><option>Swahili</option><option>Hausa</option></select><div className="switch-row"><span>Accent tolerant</span><button className="switch on" aria-label="Toggle accent tolerant"/></div><div className="switch-row"><span>Persist transcript</span><button className="switch on" aria-label="Toggle transcript persistence"/></div></div><div className="prop-block"><div className="prop-block-title">Actions <ChevronDown size={13}/></div><div className="prop-actions"><button className="btn btn-ghost"><Play size={13}/> Test node</button><button className="btn btn-ghost"><Copy size={13}/> Duplicate</button>{selectedNode.data.kind==='Vendor'&&<button className="btn btn-ghost" onClick={()=>setVendorOpen(true)}><Store size={13}/> Open vendor profile</button>}<button className="btn btn-danger" onClick={()=>{setNodes(ns=>ns.filter(n=>n.id!==selected));setSelected('')}}><Trash2 size={13}/> Delete node</button></div></div></>}</aside>
    </div>
    <button className="chat-launcher" style={{bottom:22,right:22}} onClick={()=>setVoiceOpen(true)} aria-label="Open voice canvas"><Mic2 size={22}/><span className="launcher-badge"/></button>
    {voiceOpen&&<VoiceOverlay onClose={()=>setVoiceOpen(false)} onCommand={(cmd)=>{if(cmd.includes('condition'))addNode(['Approval condition','Condition','#f5ad32','branch']);if(cmd.includes('Execute'))execute()}}/>}
    {vendorOpen&&<VendorModal onClose={()=>setVendorOpen(false)} onPO={()=>{setVendorOpen(false);setPoOpen(true)}}/>}
    {poOpen&&<POModal onClose={()=>setPoOpen(false)}/>}
  </div>;
}

function VoiceOverlay({onClose,onCommand}:{onClose:()=>void;onCommand:(s:string)=>void}){const bars=[28,50,88,44,98,67,112,54,91,35,75,102,46,85,63,32,69];return <div className="voice-modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="voice-modal" role="dialog" aria-modal="true" aria-label="Voice canvas assistant"><div className="voice-modal-top"><div><p className="eyebrow" style={{color:'#67e8f9',marginBottom:6}}><span className="eyebrow-dot"/> Voice canvas</p><strong style={{fontSize:20}}>What should we build?</strong></div><button onClick={onClose} aria-label="Close voice assistant"><X size={17}/></button></div><div className="dual-viz"><div className="viz-box">{bars.map((h,i)=><span key={i} style={{'--h':`${h}px`,animationDelay:`${i*.03}s`} as React.CSSProperties}/>)}</div><div className="viz-box"><svg className="wave-svg" viewBox="0 0 260 100"><path d="M0 50 C20 10 35 90 55 50 S90 15 110 50 S145 85 165 50 S200 5 220 50 S245 80 260 50"/></svg></div></div><div className="transcript"><span className="transcript-label">Listening · English (Nigeria)</span><p>“Add a condition node after vendor lookup…”<i className="cursor"/></p></div><div className="command-chips">{['Add a condition node','Find preferred Lagos vendors','Execute workflow'].map(c=><button key={c} onClick={()=>onCommand(c)}>{c}</button>)}</div></div></div>}

function VendorModal({onClose,onPO}:{onClose:()=>void;onPO:()=>void}){return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="market-modal" role="dialog" aria-modal="true"><div className="modal-cover"><button className="modal-close" onClick={onClose}><X size={17}/></button><div className="modal-avatar" style={{background:'linear-gradient(135deg,#f97316,#f5ad32)'}}>KP</div></div><div className="modal-body"><span className="tag tag-orange">PREFERRED VENDOR</span><h2>Kora Packaging Ltd.</h2><p className="muted" style={{fontSize:12}}>Flexible packaging · Lagos, Nigeria · Vendor since 2021</p><div className="stats-ribbon" style={{gridTemplateColumns:'repeat(3,1fr)'}}><div className="stat"><strong>96%</strong><span>Performance</span></div><div className="stat"><strong>₦15m</strong><span>Credit limit</span></div><div className="stat"><strong>Net 30</strong><span>Payment terms</span></div></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12,margin:'20px 0'}}><div><span className="field-label">Primary contact</span><strong style={{fontSize:12}}>Lola Adeyemi</strong><p className="muted" style={{fontSize:10}}>lola@korapack.ng · +234 801 234 0098</p></div><div><span className="field-label">Compliance</span><strong style={{fontSize:12}}>All documents current</strong><p className="muted" style={{fontSize:10}}>CAC · TIN · Insurance verified</p></div></div><div className="modal-actions"><button className="btn btn-primary" onClick={onPO}><ShoppingCart size={14}/> Create purchase order</button><button className="btn btn-ghost">View documents</button></div></div></div></div>}
function POModal({onClose}:{onClose:()=>void}){const [created,setCreated]=useState(false);return <div className="modal-backdrop"><div className="market-modal" role="dialog" aria-modal="true"><div className="modal-body">{created?<div style={{textAlign:'center',padding:'35px 0'}}><span className="card-icon" style={{margin:'0 auto 20px',color:'#118342',background:'#e8f9ee'}}><ClipboardList/></span><h2>PO draft created</h2><p className="muted">PO-2026-0841 was routed to Finance for approval.</p><button className="btn btn-primary" onClick={onClose}>Back to canvas</button></div>:<><div style={{display:'flex',justifyContent:'space-between'}}><div><span className="tag tag-orange">NEW PURCHASE ORDER</span><h2>Kora Packaging Ltd.</h2></div><button className="modal-close" style={{position:'static'}} onClick={onClose}><X size={17}/></button></div><label className="field-label">Description</label><input className="field" defaultValue="Printed flexible packaging · Q3 run"/><div style={{display:'grid',gridTemplateColumns:'2fr 1fr 1fr',gap:8}}><div><label className="field-label">Line item</label><input className="field" defaultValue="Packaging rolls"/></div><div><label className="field-label">Quantity</label><input className="field" defaultValue="500"/></div><div><label className="field-label">Unit price</label><input className="field" defaultValue="₦4,200"/></div></div><div className="stats-ribbon" style={{gridTemplateColumns:'repeat(3,1fr)'}}><div className="stat"><span>Subtotal</span><strong style={{fontSize:17}}>₦2.10m</strong></div><div className="stat"><span>Tax · 7.5%</span><strong style={{fontSize:17}}>₦157.5k</strong></div><div className="stat"><span>Total</span><strong style={{fontSize:17}}>₦2.26m</strong></div></div><div className="modal-actions"><button className="btn btn-primary" onClick={()=>setCreated(true)}>Create & route approval</button><button className="btn btn-ghost" onClick={onClose}>Save draft</button></div></>}</div></div></div>}
