'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, Bot, ExternalLink, MessageSquare, Search, X, Zap } from 'lucide-react';
import { Header } from './Header';import { Footer } from './Footer';import { ChatWidget } from './ChatWidget';
import { categories, marketplaceItems, type MarketplaceCategory, type MarketplaceItem } from '@/data/marketplace';

export function MarketplacePage(){
  const [cat,setCat]=useState<'ALL'|MarketplaceCategory>('ALL');const [query,setQuery]=useState('');const [item,setItem]=useState<MarketplaceItem|null>(null);
  const items=useMemo(()=>marketplaceItems.filter(x=>(cat==='ALL'||x.category===cat)&&(x.title+' '+x.features.join(' ')).toLowerCase().includes(query.toLowerCase())),[cat,query]);
  return <><Header/><main><section className="page-hero"><div className="container"><span className="eyebrow" style={{color:'#ffcc33'}}><span className="eyebrow-dot"/> Ase marketplace</span><h1>Intelligence you can inspect.</h1><p>Explore curated agent concepts, workflow previews and connector targets. Listings open as editable demos; they are not verified production integrations.</p></div></section><div className="filter-bar"><div className="container filters"><button className={`filter-btn ${cat==='ALL'?'active':''}`} onClick={()=>setCat('ALL')}>All solutions</button>{categories.map(c=><button className={`filter-btn ${cat===c?'active':''}`} key={c} onClick={()=>setCat(c)}>{c}</button>)}<input className="search-wide" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search marketplace…" aria-label="Search marketplace"/></div></div><section className="section"><div className="container"><div className="section-head"><div><p className="eyebrow"><span className="eyebrow-dot"/> {items.length} curated solutions</p><h2 className="h2" style={{fontSize:42}}>Find your starting point.</h2></div><p className="lede" style={{fontSize:15}}>Every listing is a curated preview that can seed an editable canvas demo.</p></div><div className="catalog">{items.map((x)=><MarketplaceCard item={x} onOpen={()=>setItem(x)} key={x.id}/>)}</div>{!items.length&&<div style={{textAlign:'center',padding:80}}><Search size={28} style={{margin:'0 auto 15px',color:'#999'}}/><h3>No solutions found</h3><p className="muted">Try another search or category.</p></div>}</div></section><CreatorCTA/></main><Footer/><ChatWidget/>{item&&<DetailModal item={item} onClose={()=>setItem(null)}/>}</>;
}
function MarketplaceCard({item,onOpen}:{item:MarketplaceItem;onOpen:()=>void}){return <button className="catalog-card" onClick={onOpen} style={{textAlign:'left'}}><span className="catalog-avatar">{item.category.split(' ').map(x=>x[0]).join('').slice(0,2)}</span><span className="category">{item.category}</span><h3>{item.title}</h3><div className="feature-list">{item.features.map(f=><span className="tag" key={f}>{f}</span>)}</div><div className="catalog-meta"><span>Curated demo listing</span><ArrowRight size={14}/></div></button>}
function DetailModal({item,onClose}:{item:MarketplaceItem;onClose:()=>void}){const closeRef=useRef<HTMLButtonElement>(null);useEffect(()=>{const f=(e:KeyboardEvent)=>e.key==='Escape'&&onClose();document.addEventListener('keydown',f);document.body.style.overflow='hidden';closeRef.current?.focus();return()=>{document.removeEventListener('keydown',f);document.body.style.overflow=''}},[onClose]);return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="market-modal" role="dialog" aria-modal="true" aria-label={`${item.title} details`}><div className="modal-cover"><button ref={closeRef} className="modal-close" onClick={onClose} aria-label="Close"><X size={18}/></button><span className="modal-avatar">{item.category.split(' ').map(x=>x[0]).join('').slice(0,2)}</span></div><div className="modal-body"><span className="tag tag-purple">{item.category}</span><h2>{item.title}</h2><div className="modal-stats"><span>Preview · no external adapter verified</span>{item.conversational&&<span style={{color:'#22221f'}}><MessageSquare size={13} style={{display:'inline',verticalAlign:-2}}/> Conversational UI concept</span>}</div><p className="lede" style={{fontSize:14,margin:'20px 0'}}>{item.description}</p><h3 style={{fontSize:12}}>Key capabilities</h3><div className="modal-features">{item.features.map(f=><div className="modal-feature" key={f}><Zap size={13} style={{display:'inline',verticalAlign:-2,color:'#22221f',marginRight:6}}/>{f}</div>)}</div><div className="modal-actions"><Link className="btn btn-dark" style={{flex:1}} href={`/app/canvas?template=${item.id}`}>Open demo in canvas <ArrowRight size={14}/></Link><Link className="btn btn-light" style={{flex:1}} href="/resources">View documentation <ExternalLink size={14}/></Link></div></div></div></div>}
function CreatorCTA(){return <section className="section section-dark"><div className="container"><div className="section-head"><div><p className="eyebrow" style={{color:'#ffcc33'}}><span className="eyebrow-dot"/> Build with Ase</p><h2 className="h2">Prototype. Review. Prepare.</h2></div><p className="lede" style={{color:'#9aa4b5'}}>Shape reusable operating patterns while the publishing, review and commercial rails are still being designed.</p></div><div className="card-grid" style={{gridTemplateColumns:'repeat(3,1fr)'}}>{[['Prototype a pattern','Shape agents and reusable automations on the current canvas.'],['Prepare a submission','Document controls, evidence and integration requirements.'],['Publishing target','Review, pricing and revenue sharing are not yet implemented.']].map(([t,p])=><div className="value-card" style={{background:'#111827',borderColor:'rgba(255,255,255,.1)',minHeight:230}} key={t}><span className="card-icon"><Bot size={19}/></span><h3 style={{color:'white'}}>{t}</h3><p style={{color:'#8e98a8'}}>{p}</p></div>)}</div></div></section>}
